<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.quico</groupId>
        <artifactId>quico</artifactId>
        <version>3.9.2</version>
    </parent>
    <artifactId>quico-srhelper</artifactId>
    <name>quico-srhelper</name>
    <dependencies>
        <!-- 核心模块-->
        <dependency>
            <groupId>com.quico</groupId>
            <artifactId>quico-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
